Repository Joystream/apps, pull requests merged in 2019-05, with the labels that each got.

#160 Improve UX on Upload tab
  packages/joy-media/src/Upload.tsx
  packages/joy-media/src/View.tsx
  packages/joy-media/src/index.css
Labels: ux

#163 Edit my content metadata
  packages/joy-media/src/EditMeta.tsx
  packages/joy-media/src/StorageProvider.tsx
  packages/joy-media/src/Upload.tsx
  packages/joy-media/src/View.tsx
  packages/joy-media/src/index.css
  packages/joy-media/src/index.tsx
  packages/joy-media/src/utils.ts
  packages/joy-members/src/EditForm.tsx
  packages/joy-utils/src/Section.tsx
Labels: new feature

#189 Make joy-types package into a reusable standalone npm package
  packages/joy-types/README.md
  packages/joy-types/package.json
  packages/joy-types/src/media.ts
  packages/joy-types/tsconfig.json
Labels: refactoring
